### ISSUE TITLE
Issue on the Laravel 9.2

### ISSUE THREAD

**Issue by reinhardnav** [luilliarcec/laravel-table#1]
Problem 1
    - luilliarcec/laravel-table[3.2.0, ..., 3.2.1] require laravel/framework ^7.0|^8.0 -> found laravel/framework[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but the package is fixed to v9.17.0 (lock file version) by a partial updat
e and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires luilliarcec/laravel-table ^3.2 -> satisfiable by luilliarcec/laravel-table[3.2.0, 3.2.1].

is there any chance to update to support laravel 9.2^?

**Comment by luilliarcec** [comment]
Added support for L9

**Comment by reinhardnav** [comment]
thanks
